### PR TITLE
Add to_regtypemod() Function

### PR DESCRIPTION
**Pull request by theory**
[Commitfest Submission](https://commitfest.postgresql.org/47/4807/)

### CODE REVIEW

**Comment by theory** [comment]
Doc build works, function exists, but the simple test I've added returns an error:

```
SELECT * FROM parse_type('text') p(typid, typmod);
ERROR:  a column definition list is required for functions returning "record"
LINE 1: SELECT * FROM parse_type('text') p(typid, typmod);
                      ^
```

Ideas for how to fix this? @ewie? I assume I need to tell the catalog about the record type or something…

**Comment by ewie** [comment]
> I assume I need to tell the catalog about the record type or something…

For example, `pg_identify_object()` returns `record` and the fields are treated as `OUT` arguments and are defined with `proallargtypes`, `proargmodes`, and `proargnames`:

```perl
{ oid => '3839',
  descr => 'get machine-parseable identification of SQL object',
  proname => 'pg_identify_object', provolatile => 's', prorettype => 'record',
  proargtypes => 'oid oid int4',
  proallargtypes => '{oid,oid,int4,text,text,text,text}',
  proargmodes => '{i,i,i,o,o,o,o}',
  proargnames => '{classid,objid,objsubid,type,schema,name,identity}',
  prosrc => 'pg_identify_object' },
```

https://github.com/theory/postgres/blob/3c121be3666928ba8827335fb66dc5c08e925a48/src/include/catalog/pg_proc.dat#L6352,L6359

**Comment by theory** [comment]
Ah, thank you! OUT variables always mess with me (I rarely use them).

**Comment by theory** [comment]
[Patch submitted](https://commitfest.postgresql.org/47/4807/)

**Comment by theory** [comment]
Merge in 1218ca9 🎉

**Pull request closed without merging**
